// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLZMB3G0QhTjO9FXDhLku_98gg1jIjqw',
    appId: '1:410275322225:web:d4397c6b8942cd5ed83ed0',
    messagingSenderId: '410275322225',
    projectId: 'chaty-8c5ac',
    authDomain: 'chaty-8c5ac.firebaseapp.com',
    storageBucket: 'chaty-8c5ac.firebasestorage.app',
    measurementId: 'G-M9J6RRM8X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsggjHflSvq32NANQ2nj_vEDArmV8_yKY',
    appId: '1:410275322225:android:df98225079de6f72d83ed0',
    messagingSenderId: '410275322225',
    projectId: 'chaty-8c5ac',
    storageBucket: 'chaty-8c5ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYSZMJE_OkSUvGgUvUOVw3r7m3-uwQsqw',
    appId: '1:410275322225:ios:d1e6810bccb141a6d83ed0',
    messagingSenderId: '410275322225',
    projectId: 'chaty-8c5ac',
    storageBucket: 'chaty-8c5ac.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYSZMJE_OkSUvGgUvUOVw3r7m3-uwQsqw',
    appId: '1:410275322225:ios:d1e6810bccb141a6d83ed0',
    messagingSenderId: '410275322225',
    projectId: 'chaty-8c5ac',
    storageBucket: 'chaty-8c5ac.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLZMB3G0QhTjO9FXDhLku_98gg1jIjqw',
    appId: '1:410275322225:web:711b4cfd8bec4868d83ed0',
    messagingSenderId: '410275322225',
    projectId: 'chaty-8c5ac',
    authDomain: 'chaty-8c5ac.firebaseapp.com',
    storageBucket: 'chaty-8c5ac.firebasestorage.app',
    measurementId: 'G-R7JQNPFZVR',
  );

}